package com.careercompass.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

/**
 * Response body for FR-JS-14/21 (skill profile dashboard — bar chart of strengths/weaknesses).
 *
 * <p>{@code skills} is ordered by {@code priority} — shortfall weighted by how much of the job
 * market asks for the skill — so the frontend can render it directly without re-sorting. That is
 * the order the AI contract asks for in as many words: rank on priority, not on the raw gap.
 * Ordering by raw score instead put every unstudied skill at the top in arbitrary order, which is
 * a list of everything the student has not done rather than a list of what to do next.
 */
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SkillDashboardResponse {

    private Integer jobseekerId;
    private String careerPathTitle;

    /** Java-issued identity of this persisted projection refresh. */
    private String vectorVersion;

    /** Taxonomy version reported by the AI service, when available. */
    private String taxonomyVersion;

    /** 0-100 overall readiness score for the selected career path. */
    private Integer overallReadinessPercent;

    private List<SkillLevelResponse> skills;

    /**
     * Job postings the career path's requirements were derived from — the denominator behind
     * every skill's {@code importancePercent}. Null when the AI service reports none.
     */
    private Integer sampleSize;

    /** ISO-8601 — when those postings were collected, so the page can date its own claim. */
    private String marketCapturedAt;

    /**
     * How many transcript courses actually fed this dashboard, and which ones could not.
     *
     * <p>A skill reads "missing" either because the student never studied it or because the
     * course that teaches it has no syllabus extracted yet. Only these fields let the page tell
     * the reader which of the two happened, and without them it silently blames the student for
     * the system's own gap in coverage.
     */
    private Integer coursesCounted;

    private List<SkippedCourseResponse> coursesSkipped;

    /**
     * Of {@code coursesCounted}, how many rest on a synthetic demo syllabus.
     *
     * <p>Non-zero only when the demo corpus is enabled. The page must say so when it is: a
     * profile built from invented coursework presented as a real academic record is exactly the
     * claim this field exists to stop.
     */
    private Integer syntheticCounted;

    /**
     * Classification counts split by demand band, keyed critical/important/useful, each carrying
     * strong, moderate, weak and total.
     *
     * <p>Lets the dashboard say "you meet 4 of the 11 things this career insists on" rather than
     * "4 of 129 requirements", which is true and tells a student nothing.
     */
    private Map<String, Map<String, Integer>> bandSummary;

    /**
     * Plain-language summary of the gap, generated by the AI service from numbers that are
     * already final. Null when unavailable — the dashboard is complete without it.
     */
    private String narrative;

    /**
     * True if this dashboard was built from quiz results (FR-JS-20/21);
     * false if it fell back to grade-based scoring only (FR-JS-22).
     */
    private boolean basedOnQuizResults;
}
